spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/after_sales_support
    username: root
    password: Mehta@151
  jpa:
    generate-ddl: false
    show-true: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect